ci: update

diff --git a/.github/workflows/build-and-release.yml b/.github/workflows/build-and-release.yml
--- a/.github/workflows/build-and-release.yml
+++ b/.github/workflows/build-and-release.yml
@@ -31,7 +31,19 @@ jobs:
           cache: 'pnpm'
 
       - name: Install dependencies
-        run: pnpm install && echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"
+        run: pnpm install
+
+      - name: Check if NPM_TOKEN is available
+        run: |
+          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
+            echo "ERROR: NPM_TOKEN is empty or not available"
+            exit 1
+          else
+            echo "NPM_TOKEN is available and not empty"
+            echo "Token length: ${#NODE_AUTH_TOKEN}"
+          fi
+        env:
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
 
       - name: Build
         run: |
@@ -43,3 +55,5 @@ jobs:
           less .npmrc
           npm whoami
           npm publish --access public
+     env:
+          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
